/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give Consent */
        post: operations["give_consent_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patient View */
        get: operations["patient_view_r__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Queue */
        get: operations["review_queue_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Review */
        post: operations["sign_review_review__study_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study */
        get: operations["get_study_study__study_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/{study_id}/patient-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Patient Link */
        post: operations["patient_link_study__study_id__patient_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/{study_id}/tiles/{tile_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tile */
        get: operations["get_tile_study__study_id__tiles__tile_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_analyze_post */
        Body_analyze_analyze_post: {
            /**
             * Consentid
             * Format: uuid
             */
            consentId: string;
            /**
             * File
             * @description Fundus image, PNG or JPEG
             */
            file: string;
            /**
             * Patientref
             * Format: uuid
             */
            patientRef: string;
        };
        /** ConsentRequest */
        ConsentRequest: {
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "mr";
            /**
             * Noticehash
             * @description sha256 of the notice shown
             */
            noticeHash: string;
            /**
             * Patientref
             * @description Existing patient; omit to register a new patient
             */
            patientRef?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Purpose
             * @constant
             */
            purpose: "screening";
        };
        /** ConsentResponse */
        ConsentResponse: {
            /**
             * Consentid
             * Format: uuid
             */
            consentId: string;
            /**
             * Patientref
             * Format: uuid
             */
            patientRef: string;
        };
        /** Criterion */
        Criterion: {
            /** Detail */
            detail?: {
                [key: string]: number | string | boolean;
            };
            /** Grade */
            grade: number;
            /** Key */
            key: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Contractversion
             * @default 1.1
             * @constant
             */
            contractVersion: "1.1";
            /** Databaseready */
            databaseReady: boolean;
            /** Engine */
            engine: string;
            /** Engineready */
            engineReady: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Storageready */
            storageReady: boolean;
        };
        /** PatientLinkRequest */
        PatientLinkRequest: {
            /** Phone */
            phone: string;
        };
        /** PatientLinkResponse */
        PatientLinkResponse: {
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Token */
            token: string;
        };
        /**
         * PatientView
         * @description What the patient link shows: the signed decision in lay terms, never a grade.
         */
        PatientView: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "REFER" | "ROUTINE" | "RETAKE";
            /**
             * Laterality
             * @enum {string}
             */
            laterality: "OD" | "OS" | "unknown";
            /** Retakeguidancekey */
            retakeGuidanceKey: string | null;
            /** Reviewed */
            reviewed: boolean;
            /**
             * Screenedat
             * Format: date-time
             */
            screenedAt: string;
        };
        /** Quality */
        Quality: {
            /**
             * Failuremode
             * @enum {string}
             */
            failureMode: "none" | "defocus" | "underexposed" | "overexposed" | "partial_fov" | "media_opacity";
            /** Phash */
            phash: string;
            /** Score */
            score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accept" | "enhance" | "reject";
        };
        /**
         * QueuedBody
         * @description 503 body when NX_CACHED_MODE is on and the image is not in the inference cache.
         */
        QueuedBody: {
            /** Reason */
            reason: string;
            /**
             * Status
             * @constant
             */
            status: "queued";
        };
        /** ReviewQueueItem */
        ReviewQueueItem: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "REFER" | "ROUTINE" | "RETAKE";
            /** Flag */
            flag: ("same_image_other_patient" | "repeat_screening") | null;
            /** Grade */
            grade: number | null;
            /** Preferable */
            pReferable: number | null;
            /**
             * Studyid
             * Format: uuid
             */
            studyId: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "REFER" | "ROUTINE" | "RETAKE";
            /** Elapsedms */
            elapsedMs?: number | null;
            /** Grade */
            grade: number | null;
            /** Reasonchip */
            reasonChip?: ("image_artefact" | "lesion_miscount" | "disc_region_confusion" | "dme_missed") | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "REFER" | "ROUTINE" | "RETAKE";
            /** Grade */
            grade: number | null;
            /** Overturn */
            overturn: boolean;
            /**
             * Reviewid
             * Format: uuid
             */
            reviewId: string;
            /**
             * Studyid
             * Format: uuid
             */
            studyId: string;
        };
        /** StudyEvidence */
        StudyEvidence: {
            /** Criterionkey */
            criterionKey: string | null;
            /** Cropurl */
            cropUrl: string;
            /** Distancetofoveadd */
            distanceToFoveaDD: number | null;
            /**
             * Quadrant
             * @enum {string}
             */
            quadrant: "ST" | "SN" | "IT" | "IN";
            /**
             * Type
             * @enum {string}
             */
            type: "MA" | "HE" | "EX" | "SE" | "NV_PROXY";
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * StudyResponse
         * @description Contract 6.2 — the engine result as served by the gateway.
         */
        StudyResponse: {
            /** Cfghash */
            cfgHash: string;
            /**
             * Contractversion
             * @constant
             */
            contractVersion: "1.1";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
            /**
             * Decision
             * @enum {string}
             */
            decision: "REFER" | "ROUTINE" | "RETAKE";
            /** Evidence */
            evidence: components["schemas"]["StudyEvidence"][] | null;
            /** Fhirbundle */
            fhirBundle: {
                [key: string]: unknown;
            };
            /** Flag */
            flag: ("same_image_other_patient" | "repeat_screening") | null;
            /** Gradcamurl */
            gradcamUrl?: string | null;
            /** Grade */
            grade: number | null;
            /**
             * Laterality
             * @enum {string}
             */
            laterality: "OD" | "OS" | "unknown";
            /** Llp */
            llp?: number | null;
            /** Modelver */
            modelVer: string;
            /** Preferable */
            pReferable: number | null;
            /** Patientref */
            patientRef: string;
            /** Posterior */
            posterior: number[] | null;
            quality: components["schemas"]["Quality"];
            /** Reporturl */
            reportUrl?: string | null;
            /** Retakeguidancekey */
            retakeGuidanceKey?: string | null;
            /** Reviewrequired */
            reviewRequired: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "matlab" | "cache";
            /** Studyid */
            studyId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedBody"] | components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    give_consent_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    patient_view_r__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    sign_review_review__study_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_study_study__study_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patient_link_study__study_id__patient_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientLinkResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_study__study_id__tiles__tile_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                tile_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Redirect to a presigned tile URL */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
