/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_analyze_post */
        Body_analyze_analyze_post: {
            /** Consentid */
            consentId: string;
            /**
             * File
             * @description Fundus image, PNG or JPEG
             */
            file: string;
            /** Patientref */
            patientRef: string;
        };
        /** Criterion */
        Criterion: {
            /** Detail */
            detail?: {
                [key: string]: number | string | boolean;
            };
            /** Grade */
            grade: number;
            /** Key */
            key: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Contractversion
             * @default 1.0
             * @constant
             */
            contractVersion: "1.0";
            /** Engine */
            engine: string;
            /** Engineready */
            engineReady: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** Quality */
        Quality: {
            /**
             * Failuremode
             * @enum {string}
             */
            failureMode: "none" | "defocus" | "underexposed" | "overexposed" | "partial_fov" | "media_opacity";
            /** Phash */
            phash: string;
            /** Score */
            score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accept" | "enhance" | "reject";
        };
        /** StudyEvidence */
        StudyEvidence: {
            /** Criterionkey */
            criterionKey: string | null;
            /** Cropurl */
            cropUrl: string;
            /** Distancetofoveadd */
            distanceToFoveaDD: number | null;
            /**
             * Quadrant
             * @enum {string}
             */
            quadrant: "ST" | "SN" | "IT" | "IN";
            /**
             * Type
             * @enum {string}
             */
            type: "MA" | "HE" | "EX" | "SE" | "NV_PROXY";
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * StudyResponse
         * @description Contract 6.2 — the engine result as served by the gateway.
         */
        StudyResponse: {
            /** Cfghash */
            cfgHash: string;
            /**
             * Contractversion
             * @constant
             */
            contractVersion: "1.0";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Criteria */
            criteria: components["schemas"]["Criterion"][];
            /**
             * Decision
             * @enum {string}
             */
            decision: "REFER" | "ROUTINE" | "RETAKE";
            /** Evidence */
            evidence: components["schemas"]["StudyEvidence"][] | null;
            /** Fhirbundle */
            fhirBundle: {
                [key: string]: unknown;
            };
            /** Flag */
            flag: ("same_image_other_patient" | "repeat_screening") | null;
            /** Gradcamurl */
            gradcamUrl?: string | null;
            /** Grade */
            grade: number | null;
            /**
             * Laterality
             * @enum {string}
             */
            laterality: "OD" | "OS" | "unknown";
            /** Llp */
            llp?: number | null;
            /** Modelver */
            modelVer: string;
            /** Preferable */
            pReferable: number | null;
            /** Patientref */
            patientRef: string;
            /** Posterior */
            posterior: number[] | null;
            quality: components["schemas"]["Quality"];
            /** Reporturl */
            reportUrl?: string | null;
            /** Retakeguidancekey */
            retakeGuidanceKey?: string | null;
            /** Reviewrequired */
            reviewRequired: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "matlab" | "cache";
            /** Studyid */
            studyId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
