"""Write gitignored .env.tier1 and run Supabase migrations. Secrets via env or stdin — never logged."""

from __future__ import annotations

import os
import secrets
import sys
import subprocess
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
REF = "imlojjdueuesjwznuzez"
POOL = "aws-0-ap-south-1.pooler.supabase.com"


def _require(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        print(f"Set {name} in the environment before running this script.", file=sys.stderr)
        sys.exit(1)
    return value


def main() -> int:
    db_password = _require("SUPABASE_DB_PASSWORD")
    s3_key = _require("SUPABASE_S3_ACCESS_KEY")
    s3_secret = _require("SUPABASE_S3_SECRET_KEY")
    oidc_issuer = os.environ.get("OIDC_ISSUER", "").strip()
    cors = os.environ.get(
        "CORS_ORIGINS",
        "https://netrasetu.vercel.app,https://netrasetu-dyixy377k-gurjas2112s-projects.vercel.app",
    ).strip()

    gw_pass = os.environ.get("GATEWAY_DB_PASSWORD") or secrets.token_hex(16)
    worker_pass = os.environ.get("WORKER_DB_PASSWORD") or secrets.token_hex(16)
    patient_secret = os.environ.get("PATIENT_TOKEN_SECRET") or secrets.token_hex(32)
    enc = quote(db_password, safe="")

    # Session pooler (IPv4-friendly). Direct db.* host is often IPv6-only.
    admin = (
        f"postgresql://postgres.{REF}:{enc}@{POOL}:5432/postgres?sslmode=require"
    )
    gateway_url = (
        f"postgresql://gateway.{REF}:{quote(gw_pass, safe='')}@{POOL}:5432/postgres?sslmode=require"
    )
    worker_url = (
        f"postgresql://worker.{REF}:{quote(worker_pass, safe='')}@{POOL}:5432/postgres?sslmode=require"
    )
    keepalive = gateway_url

    lines = [
        "# Tier 1 — gitignored. Generated by scripts/setup_tier1_supabase.py",
        f"ADMIN_DATABASE_URL={admin}",
        f"DATABASE_URL={gateway_url}",
        f"GATEWAY_DB_PASSWORD={gw_pass}",
        f"WORKER_DB_PASSWORD={worker_pass}",
        f"PATIENT_TOKEN_SECRET={patient_secret}",
        "GATEWAY_ENGINE=fake",
        "GATEWAY_MODE=queue",
        f"S3_ENDPOINT=https://{REF}.storage.supabase.co/storage/v1/s3",
        "S3_REGION=ap-south-1",
        "S3_BUCKET=netrasetu",
        f"S3_ACCESS_KEY={s3_key}",
        f"S3_SECRET_KEY={s3_secret}",
        "PRESIGN_TTL_SECONDS=3600",
        "CACHE_ENABLED=true",
        f"CORS_ORIGINS={cors}",
        "OIDC_AUDIENCE=netrasetu-gateway",
        f"SUPABASE_KEEPALIVE_URL={keepalive}",
    ]
    if oidc_issuer:
        lines.append(f"OIDC_ISSUER={oidc_issuer}")
    else:
        lines.append("# OIDC_ISSUER=https://<keycloak-host>/realms/netrasetu")

    out = ROOT / ".env.tier1"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out.name} (OIDC_ISSUER {'set' if oidc_issuer else 'still needed'})")

    env = os.environ.copy()
    for line in lines:
        if line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k] = v

    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "migrate.py")],
        cwd=ROOT,
        env=env,
        check=False,
    )
    if result.returncode != 0:
        return result.returncode

    service_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()
    if service_key:
        import json
        import urllib.error
        import urllib.request

        req = urllib.request.Request(
            f"https://{REF}.supabase.co/storage/v1/bucket",
            data=json.dumps({"name": "netrasetu", "public": False}).encode(),
            headers={
                "Authorization": f"Bearer {service_key}",
                "Content-Type": "application/json",
                "apikey": service_key,
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=30):
                print("Created storage bucket netrasetu.")
        except urllib.error.HTTPError as exc:
            if exc.code == 409:
                print("Storage bucket netrasetu already exists.")
            else:
                print(f"Storage bucket setup returned HTTP {exc.code} — create 'netrasetu' in the dashboard if needed.")

    print("Migrations applied on Supabase.")
    print("Next: deploy Keycloak, set OIDC_ISSUER in .env.tier1, railway up, vercel --prod.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
